FROM ghcr.io/astral-sh/uv:bookworm-slim

ENV PUID=1000
ENV PGID=1000

RUN apt-get update && \
    apt-get install tini gosu dos2unix ca-certificates build-essential --yes --no-install-recommends && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

ENV UV_LINK_MODE=copy

# Use Python 3.12 to ensure compatible wheels are available
ENV UV_PYTHON=3.12

# Set the cache directory to /tmp instead of root
ENV UV_CACHE_DIR=/tmp/.cache/uv

ENV UV_PYTHON_INSTALL_DIR=/app/.bin

# Install the project's dependencies using the lockfile and settings
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/tmp/.cache/uv \
    uv sync --no-install-project --no-dev

# Then, add the rest of the project source code and install it
# Installing separately from its dependencies allows optimal layer caching
COPY . /app
RUN --mount=type=cache,target=/tmp/.cache/uv \
    uv sync --no-dev

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

RUN chmod +x *.sh && \
    dos2unix *.sh

# Set default values to prevent issues
ENV DRYRUN="True"
ENV DEBUG_LEVEL="INFO"
ENV RUN_ONLY_ONCE="False"
ENV SLEEP_DURATION=3600
ENV SYNC_CRON=""
ENV LOG_FILE="log.log"
ENV MARK_FILE="mark.log"
ENV CONFIG_DIR="/config"
ENV SYNC_PLAYLISTS="True"
ENV PLAYLIST_STATE_FILE="playlist_state.json"
ENV WATCHED_STATE_FILE="watched_state.json"
ENV GENERATE_GUIDS="True"
ENV GENERATE_LOCATIONS="True"
ENV MAX_THREADS=10
ENV USER_MAPPING=""
ENV LIBRARY_MAPPING=""
ENV BLACKLIST_LIBRARY=""
ENV WHITELIST_LIBRARY=""
ENV BLACKLIST_LIBRARY_TYPE=""
ENV WHITELIST_LIBRARY_TYPE=""
ENV BLACKLIST_USERS=""
ENV WHITELIST_USERS=""
ENV PLEX_BASEURL=""
ENV PLEX_TOKEN=""
ENV PLEX_USERNAME=""
ENV PLEX_PASSWORD=""
ENV PLEX_SERVERNAME=""
ENV SSL_BYPASS="False"


ENTRYPOINT ["/bin/tini", "--", "/app/entrypoint.sh"]
CMD ["python", "-u", "main.py"]
